### ISSUE TITLE
no entity window option

### ISSUE THREAD

**Issue by Nihilitior** [Antoshidza/Age-of-Sprites#10]
The project can run normally without errors, but there is no entity window option. I have it in my other ECS projects.
![image](https://github.com/user-attachments/assets/9e8f8530-edef-4ec3-af7d-2c8a54d03c63)
![image](https://github.com/user-attachments/assets/c70447d8-f1da-4227-a5b6-8a457845b53f)

**Comment by Antoshidza** [comment]
Fixed https://github.com/Antoshidza/NSprites/pull/20
