### ISSUE TITLE
Legionnaires appear wrongly when they are in their squad

### ISSUE THREAD

**Issue by laicasaane** [Antoshidza/Age-of-Sprites#4]
Don't know if this is a known issue or not.

![image](https://user-images.githubusercontent.com/1594982/209513905-a62b0716-2bb1-449c-880f-f2a97e05fcc9.png)

They look like this:
![image](https://user-images.githubusercontent.com/1594982/209514089-ce0e50ba-ad21-4bc1-b624-5b0cf6f5b9a3.png)

**Comment by Antoshidza** [comment]
It happens only in build AFAIK and only when animation switched, I'll try to figure out what goes wrong. Probably it happens because UVs baked from atlas which isn't the same in build and in editor

**Comment by laicasaane** [comment]
> It happens only in build

I don't get what you mean. I captured the bug in the editor.

**Comment by kstars111** [comment]
the sprite is split like the second picture in the editor view, but in play view the sprite is displayed properly

**Comment by laicasaane** [comment]
@kstars111 it doesn't display properly for me in the game view. The first image is from the game view.

![image](https://user-images.githubusercontent.com/1594982/209938556-e6118841-bd19-4ac5-b889-db8b950dcdec.png)

**Comment by kstars111** [comment]
I must admit I noticed the same initially, but then it seemed to resolve.  Not sure if I updated the project and that made the difference.  Is your project the latest version? ![image](https://user-images.githubusercontent.com/96685627/209939623-31909843-88ef-4b2e-be63-79f26d948ce2.png)

**Comment by laicasaane** [comment]
@kstars111 I'm at the latest commit. Btw I'm opening the project in Unity 2022.2.1. Could that be a problem?

**Comment by Antoshidza** [comment]
@laicasaane no, project intened to used with 2022.2.x. All this mess is because of unity sprite atlas. It work differently editor/play/build time + it can't just simply provide result of packing as final texture because of unity want to react at any sprite was changed during editor time, so texture will be invalidated. I think about using third party solutions and just import dumb atlas as solid texture without using unity sprite atlas. Baking just can't bake proper UVs.

**Comment by laicasaane** [comment]
@Antoshidza Thanks! It's great to see the fix on the first work day of the year. And I think the perf has improved a bit, the number of batches was over 20 at the time I posted this issue.
