### ISSUE TITLE
The player builds stop working for Unity 2022.2.2

### ISSUE THREAD

**Issue by laicasaane** [Antoshidza/Age-of-Sprites#6]
After upgrading the project to Unity 2022.2.2, Windows and Android builds stop showing sprites. I've reported this problem to Unity though I still post the issue here in case you know the cause before them (usually it takes Unity nearly a month to answer my feedbacks). My main suspect is Burst 1.8.2 (previously 1.7.4 for Unity 2022.2.1).

**Comment by Antoshidza** [comment]
Problem is inside [`RegistrateRenderersSystem`](https://github.com/Antoshidza/Age-of-Sprites/blob/main/Assets/Sources/NSprites%20Foundation/Base/Systems/RegisterRenderersSystem.cs) particulary in place where code touches [`PropertiesSet`](https://github.com/Antoshidza/Age-of-Sprites/blob/main/Assets/Sources/NSprites%20Foundation/Base/Data/PropertiesSet.cs) which is null on every entity in every build run. 
More important thing is that [`PropertiesSet`](https://github.com/Antoshidza/Age-of-Sprites/blob/main/Assets/Sources/NSprites%20Foundation/Base/Data/PropertiesSet.cs) contained inside [`SpriteRenderDataToRegistrate`](https://github.com/Antoshidza/Age-of-Sprites/blob/main/Assets/Sources/NSprites%20Foundation/Base/Authoring/SpriteRenderDataToRegistrate.cs) which used to registrate unique renderers for rendering system. This class not only includes properties set but also `Material` which isn't null but loaded.
From first view it looks like something broken with baking or loading subscene data process particluary on ScriptableObjects.

**Comment by Antoshidza** [comment]
I'm so tired to build project and dancing around it in hope to extact a piece of information. But this is what I've realised:
- problem was in getting SO in managed component in build
- it happens only with SO, other instances loaded well
- it happens only with last SO in class layout, so after adding any else SO the first one loaded well and build starts render sprites because registration goes well

**Comment by Antoshidza** [comment]
Issue seems still present depending on [replay](https://forum.unity.com/threads/nullref-scriptableobject-inside-baked-managed-component-in-build-in-2022-2-2-unity.1389036/#post-8770339:~:text=This%20was%20not%20resolved%20by%20any%20mean.%20I%27ve%20just%20upgraded%20to%202022.2.4) in forum thread

**Comment by Antoshidza** [comment]
Issue seems still present depending on [replay](https://forum.unity.com/threads/nullref-scriptableobject-inside-baked-managed-component-in-build-in-2022-2-2-unity.1389036/#post-8770339:~:text=This%20was%20not%20resolved%20by%20any%20mean.%20I%27ve%20just%20upgraded%20to%202022.2.4) in forum thread
