### ISSUE TITLE
404 Link in readme

### ISSUE THREAD

**Issue by ComradeVanti** [Antoshidza/Age-of-Sprites#7]
The link to [PropertiesManifest.cs](https://github.com/Antoshidza/NSprites-Dev/blob/main/Assets/Sources/PropertiesManifest.cs) leads to a 404 page.

**Comment by Antoshidza** [comment]
@ComradeVanti thank you for mentioning. There also were another broken links. All links now respect it's actual content location in [NSprites-Foundation](https://github.com/Antoshidza/NSprites-Foundation)
